### ISSUE TITLE
Validator=True Does Not Work

### ISSUE THREAD

**Issue by joesixpack** [SimplyVC/panic_oasis#1]
I wasn't able to run PANIC before these recent v2.0..0 updates.  Did something break?

![image](https://user-images.githubusercontent.com/23145642/87791084-8bd38980-c7f6-11ea-9a83-f2d6b1fe2830.png)

Works fine with FALSE.

**Comment by joesixpack** [comment]
Hmm, no joy.  It seems like it actually tries to parse it but fails, regardless of the setting in the nodes config file.

![image](https://user-images.githubusercontent.com/23145642/87946798-57123d00-ca57-11ea-8e45-9728ec7a8940.png)

**Comment by VitalyVolozhinov** [comment]
Is your Validator registered on the Oasis Network? Is it Synced? I am not seeing your node public key in the list of registered nodes:

**Comment by joesixpack** [comment]
https://oasis.smartstake.io/pool/76

The public key is different than what you want entered in the config.  

But besides that, I'm trying to find out what is wrong with the bloody node hence why I've setup PANIC.

**Comment by joesixpack** [comment]
Hi, I found that the entity.json in near/entity was not the version for Amber.  It appears to be working now with the node public key:

Loading .env environment variables…
Current working directory set to /home/j/panic_oasis
Enabled alerting channels (general): ConsoleChannel, LogChannel, TelegramChannel, MongoChannel
Enabled alerting channels (periodic alive reminder): ConsoleChannel, LogChannel, MongoChannel
Alert types enabled = 72
Alert types disabled = 12
Trying to retrieve data from the API of oasis
Success. API is configured correctly
Trying to retrieve node name oasis from API
Success. node name is configured correctly
Trying to retrieve Node Public Key oasis from
Success. Prometheus is configured correctly
Success. Node Exporter is configured correctly
Trying to convert the Node oasis Key into a Consensus Public Key and a Tendermint Address key
Successfully converted node public key into Consensus Public Key and Tendermint Address
Please note that since no data source is an archive node for chain amber-2020-06-18-1592496000, archive monitoring will be disabled for this chain. To enable archive monitoring, please restart the alerter and modify the node config so that it contains at least one archive data source node for chain amber-2020-06-18-1592496000.
Trying to connect to https://api.github.com/repos/oasislabs/oasis-core/releases
Success.
System monitor (oasis) started.
Node monitor (oasis) started.
Telegram commands started.
GitHub monitor (Oasis) started.
PANIC INFO - oasis total bonded balance INCREASED from 0.0 to 10000.0.
PANIC INFO - oasis total shares balance INCREASED from 0.0 to 10000.0.
PANIC INFO - oasis missed 2 blocks in a row (height: 477220, total validators missing: 0).
PANIC INFO - oasis missed 3 blocks in a row (height: 477221, total validators missing: 0).
PANIC INFO - oasis missed 4 blocks in a row (height: 477222, total validators missing: 0).
PANIC WARNING - oasis missed 5 blocks in a row (height: 477223, total validators missing: 0).

**Comment by VitalyVolozhinov** [comment]
In which directory did you find the node public key?

**Comment by joesixpack** [comment]
Its in two locations, the entity.json in entity/ as well as the identity_pub.pem in node/.

**Comment by VitalyVolozhinov** [comment]
Thank you
